# Generated by Django 5.1.14 on 2026-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_ferry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='0–100. Updated via cache mid-run; persisted to DB at completion.'),
        ),
    ]
